version: '3.8'

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/lnaidu/Desktop/data/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/lnaidu/Desktop/data/mariadb
      o: bind

networks:
  inception:
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    networks:
      -  inception
    build: ./requirements/mariadb
    image: mariadb:42
    volumes: 
      - mariadb_data:/var/lib/mysql
    env_file: .env
    expose:
      - "3306"
    restart: always
  nginx:
    container_name: nginx
    volumes: 
      - wordpress_data:/var/www/html
    networks:
      -  inception
    depends_on:
      - wordpress
    image: nginx:42
    build: ./requirements/nginx
    env_file: .env
    ports:
      - "443:443"
    restart: always
  wordpress:
    container_name: wordpress
    env_file: .env
    volumes: 
      - wordpress_data:/var/www/html
    networks:
      - inception
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    restart: on-failure
    expose: 
      - "9000"

